#!/usr/bin/env bash

# Inspired on https://github.com/adriancooney/Taskfile
#
# Install an alias, to be able to simply execute `run`
# echo 'alias run=./run' >> ~/.aliases
#
# alias run=./Taskfile
# alias help=./Taskfile help

function help {
    echo "$0 <task> <args>"
    echo "Tasks:"
    compgen -A function | cat -n
}

function default {
    help
}

function build {
    docker compose -f docker-compose.prod.yml build marina
}

function push {
    docker compose -f docker-compose.prod.yml push marina
}

function deploy {
    docker buildx build -t finuras/marina:latest --platform linux/amd64 --push
}

TIMEFORMAT="Task completed in %3lR"
time "${@:-default}"
